nd is not yet developed for device DACONO

Traceback (most recent call last):
  File "src/genie/cli/commands/learn.py", line 293, in genie.cli.commands.learn.LearnCommand._retrieve_ops
  File "src/genie/ops/utils.py", line 51, in genie.ops.utils.get_ops
LookupError: Could not find the OPS under ios
